import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#e5beb2",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "outline": "#2a2a2a",
        "on-secondary-fixed": "#1a1c1c",
        "on-tertiary-fixed": "#001b3c",
        "secondary-container": "#2a2a2a",
        "primary-fixed": "#ffdbd0",
        "primary-container": "#ff5712",
        "surface": "#0e0e0e",
        "surface-variant": "#1c1b1b",
        "on-primary-fixed": "#390b00",
        "tertiary-container": "#3491ff",
        "surface-bright": "#1a1a1a",
        "on-tertiary-container": "#002955",
        "surface-container-low": "#131313",
        "surface-container-high": "#1c1c1c",
        "primary": "#ff5712",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#e2e2e2",
        "on-primary-container": "#511400",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary": "#2f3131",
        "inverse-primary": "#ac3400",
        "on-error": "#690005",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a8c8ff",
        "tertiary": "#a8c8ff",
        "surface-container": "#131313",
        "error": "#ffb4ab",
        "on-tertiary": "#003061",
        "surface-tint": "#ffb59d",
        "surface-container-lowest": "#0a0a0a",
        "surface-dim": "#0e0e0e",
        "outline-variant": "#2a2a2a",
        "background": "#0a0a0a",
        "surface-container-highest": "#252525",
        "on-secondary-fixed-variant": "#454747",
        "on-secondary-container": "#b4b5b5",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "secondary": "#c6c6c7",
        "on-tertiary-fixed-variant": "#004689",
        "on-primary-fixed-variant": "#832600",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "32px",
        gutter: "1px",
        "space-xl": "48px",
        "space-md": "20px",
        "space-sm": "12px",
        "panel-margin": "16px",
        "space-xs": "6px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-base": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "mono-label": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
